name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq for JSON parsing
        run: sudo apt-get install jq

      - name: Download Release Assets
        run: |
          # Get release data
          RELEASE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}")

          # Loop through assets and download .whl and .tar.gz files
          echo "$RELEASE_DATA" | jq -r '.assets[] | select(.name | endswith(".whl") or endswith(".tar.gz")) | .url' | while read -r ASSET_URL; do
            curl -sL -o "$(basename "$ASSET_URL")" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/octet-stream" "$ASSET_URL"
          done

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
